### ISSUE TITLE
This currently does not work with the Steam version.

### ISSUE THREAD

**Issue by rainxk2** [StarPandaBeg/ChallengePack#1]
In the game it has a new menu called mods, and it tells me if I see that I installed everything correctly.
But in the game, nor while the game is going, there is no menu to turn on or off any of the menus shown in the readme.

**Comment by h3oCharles** [comment]
1.2.2 (Steam) and BRML 2.0.3, worked flawlessly for me, RTFM

**Comment by rainxk2** [comment]
nah I tried. Does not work for me.

**Comment by StarPandaBeg** [comment]
Tried to fix it in v1.4.1. 
Download it from [releases](https://github.com/StarPandaBeg/ChallengePack/releases/latest) page.

Let me know if it helped

**Comment by rainxk2** [comment]
it worked, I forgot to reply. Thank you :)
