### ISSUE TITLE
item covers are gone after dying

### ISSUE THREAD

**Issue by h3oCharles** [StarPandaBeg/ChallengePack#2]
first time playing the patched version, so pills aren't available to me

I died, which made me get defibrillated in the bathroom.
I come back to the gameplay room and the covers are gone, despite them being there previously, because I enabled them before starting

the mod list when this was encountered:
- MSLaFaver-BugFixes-1.2.1.zip
- SmarterDealer-2.0.0.zip
- StarPanda-ChallengePack-1.4.0.zip

V1.2.2-3 (Steam + BRML V2.0.3)

**Comment by h3oCharles** [comment]
just checked the same scenario during double or nothing, same problem occurs

**Comment by StarPandaBeg** [comment]
To be honest, I haven't tested the mod much since the Steam release.
I would test it and fix in a couple of days.

**Comment by StarPandaBeg** [comment]
Fixed in v1.4.1. 
Download new version from [releases](https://github.com/StarPandaBeg/ChallengePack/releases/latest) page.

If the issue persists you can reopen it.
