### ISSUE TITLE
beer poking out of the covers

### ISSUE THREAD

**Issue by h3oCharles** [StarPandaBeg/ChallengePack#3]
![image](https://github.com/StarPandaBeg/ChallengePack/assets/8020330/68686a2a-a1e6-4f6d-a03b-2f246e6cf626)
visual glitch, nuff said

**Comment by StarPandaBeg** [comment]
Scaled covers a bit in v1.4.1. Download new version from [releases](https://github.com/StarPandaBeg/ChallengePack/releases/latest) page.

If the issue persists you can reopen it.
