### ISSUE TITLE
start button visible on all menu screens

### ISSUE THREAD

**Issue by h3oCharles** [StarPandaBeg/ChallengePack#4]
![image](https://github.com/StarPandaBeg/ChallengePack/assets/8020330/c6d26bd0-8693-424e-92e5-f1952585cd39)

its especially bad on the options menu
![image](https://github.com/StarPandaBeg/ChallengePack/assets/8020330/f22c312a-4f78-4ae1-abc5-2e34123a4c42)

**Comment by StarPandaBeg** [comment]
Fixed in v1.4.1. Download new version from [releases](https://github.com/StarPandaBeg/ChallengePack/releases/latest) page.
